### ISSUE TITLE
Discuss Architecture Patterns

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OtripleS#33]
This issue is a thread to discuss potential patterns that we could adapt in OtripleS to streamline the development of the project, the current pattern follows the Models, Brokers, Services, Controllers and Views pattern, you can learn more about the pattern in the following sessions:
[Fundamentals of Building ASP.NET Core Applications](https://www.youtube.com/watch?v=L6tLGQiKZNE)
[Fundamentals of Building ASP.NET Core Applications (Brokers)](https://www.youtube.com/watch?v=FS6NkMcXjg4)
[Fundamentals of Building ASP.NET Core Applications (Brokers & Services)](https://www.youtube.com/watch?v=xNv4iet0okg)
[Architecting Industrial Software - Services Deep Dive](https://www.youtube.com/watch?v=vZgPbneAdCM)
[Exception Handling Noise in C#](https://www.youtube.com/watch?v=ECw-eYEG2HE)

Some of the contributors on this project have proposed some patterns like MediatR and some others had concerns about exception handling - this is the thread to discuss all these ideas and dive into their details.
This issue should not be a blocker for the current or future work until the team reaches a decision about which pattern we need to follow, it's never too late because eventually the current monolith we are building should dissolve into microservices this is the current mindset behind how we are building what we are building  - building a monolith with microservices mindset.

**Comment by AgentEnder** [comment]
Just watched the video `Exception Handling Noise in C#` and I really like that idea, makes a ton of sense and seems easy to implement.

**Comment by Driedas** [comment]
First of all, I greatly appreciate the effort put into this, it's great to see so many people finding time to participate and churn out ideas and code for just the good feels of it, kudos. I'm adding my 5 cents to the discussion, nothing below is meant to be personal, or addressed to any specific person (I didn't do a git blame to check commit authors). I'm also not advocating for any changes in framework or technology in this post (however will do so if prompted), this is purely my observation and is to be taken as constructive criticism with no ill intent, purely my attempt at improving things (some of it subjectively I'm sure) and starting a dialog.

**1) project structure**
_services, entities, API controllers everything in a single project._ This would not be an issue on a small, single use, single logical deployment project. For anything larger than that, you will most likely have separate components, deployed separately (at least logically if not physically). For example handling background processes like sending emails, scheduled jobs, etc. All of these would need to host everything, including the API. It would make more sense to me to at least split out the model and services into separate assemblies and having the API as just an (or one of) optional communication layer on top of that.

**2) API**
_2.1) missing authentication_. How will the user authenticate against the API? How will his security credentials (roles or permissions) be verified? Even a hardcoded Principal to demonstrate use is alright at this stage I think.

_2.2) noise (exceptions) to signal (actual logic) ratio_ is quite high, at a glance around 3/4 of the code is catching exceptions of different types, while doing similar (or in some cases exactly the same) things with them afterwards. Doing it like this is very costly from a maintenance and awareness point of view. Developers would typically copy paste these around. Code like this belongs into an action filter that will be applied globally for all of the endpoints, and the individual controller actions are thus freed up to only handle the actual logic

_2.3) entities are being returned and accepted verbatim via the API_ including system attributes that should never be modified externally in an audited system. I made this example before, but with an interface like this it is possible to register a student with all A grades and graduated. Only a restricted set of properties should be modifiable via the API, the rest should be filled in by the system. @hassanhabib I know you mentioned that there will be some orchestration done on these to prevent a scenario like the above, but I see nothing in that direction in the project.
Do we even have a use case to update the properties of a student after registration? Unless the operator made a typo when registering, the student's name, sex, birthdate, etc remain the same throughout his stay in the institution. 

**3) service layer**
_3.1) service implementation split into 3 files._ While I admire the intent to keep things like exception handling and validation outside of the service logic, in order to get a full view of what an actual service method does you need to open 3 files and switch between them. This breaks the flow of reading the code so it is more difficult to spot potential issues with it.

_3.2) sooo many custom exception types._ I count 8 custom exceptions for the Student entity only. Why is it necessary to distinguish between them? It is not clear to me which one to use when, e. g. NotFoundStudentException and NullStudentException, InvalidStudentInputException and StudentValidationException. Are there going to be another 8 exception types for the teacher as well?
Why is it even useful to use custom exception types? Broadly speaking from an interface point of view, there are only 2 kinds of exceptions. Ones that are caused by the caller, that contain error messages that the caller will understand and will be able to do something about (e. g. validation exceptions), that can be converted to the semantics of the communication interface, e. g. 400/422 status code responses with a web API. This can be handled by a shared ValidationException or similar.
The other kind are internal exceptions, whose internals should never be revealed to the outside, merely logged and reported on. The caller should receive a generic exception messages (my favorite one being "Something happened." that I actually got when installing Windows 10 for the first time), that could be translated to a 500 status code on the API.
What is the point of the service layer handling and logging and rethrowing all of those exceptions? All of those exceptions the service layer cannot do anything useful about and may just as well let them bubble up to the caller (with the distinction above, validation exceptions separate from all other exceptions, but I don't see why differentiate between "all other"). I could maybe see a use case where you want to alert operations based on certain exception types, but all of this can be done globally, on the communication interface and the services can more or less ignore all exceptions (except validation ones and maybe others where it can actually do something useful about).

_3.3) services accept entities as parameters._ I've made this observation in a PR, but will copy it here as well.
the Student entity will grow over time. It will not (and even now is not) apparent what data is required for the registration of a new student based on the entity alone. Having a method with explicit primitive parameters makes it obvious what the required data is. I think that the student registration method only should accept primitive parameters that are required for the registration of a new student, and fill in all the rest (createddate, createdby, status, ...). 

_3.4) validation._ The validation of a student is now 200+ lines of catch and if statements. The cyclomatic complexity of this is enormous and writing all of that code is tedious, error prone and ultimately can be replaced by using a smart validation framework that allows you to apply validation rules declaratively. Even out of the box Data Annotations offer all of that functionality and could be applied straight on the entity if need be, or on a command object that would represent the intent of student registration/modification

_3.5) storage brokers_. What is the added value of these? All they do is abstract EF as the repository, which is both a leaky abstraction (e. g. necessity to do eager loading via Include, using Find where appropriate, etc) and an unnecessarily complex one. Purely for the sake of mocking, would it not suffice to expose an ISet<T>, Find<T>, SaveChanges and the ConnectionString?

_3.6) auditing._ How will this be performed? This ties a bit into the authentication system, and how the identity of the caller will flow through the system (if at all), but I'm also missing history tables attached to the entities (or something to approximate that functionality, e. g. event sourcing).

**4) model**
_4.1) There is no domain model_. From the looks of it, all entities will just be C# classes with public getters and setters. This is a viable approach for an anemic domain model with a transaction script pattern, but a domain model could be that much more than just getters and setters. The alternative would be trying to follow an always-valid approach for entities, and only exposing their state as read only, with methods designated for modifying their state. In this case e. g. Register, Suspend, Expell, etc. The Student entity would be responsible for its own validation, the service layer would essentially just retrieve a Student entity from the repository, call a method on it, and persist it back, potentially adding some orchestration on top of that (e. g. to facilitate the cooperation of multiple entities, raise events, etc)

_4.2) I like the use of EF migrations_. I have 0 experience with using these, but it looks useful at a glance.

**0) git usage**
This is maybe purely subjective, but I like to able to easily see what feature a commit belongs to, and ideally a commit would contain all of the required changes for that feature (excluding future bug fixes of course). If I take a look at the git project history, I see 33 sequential commits, one with a failing test and one with the test passing (if I'm counting correctly) for only the feature of updating a Student. What is the rationale behind this? This makes it almost impossible to do things like cherrypick a feature to be released separately, revert a feature that has proven problematic and needs to be rolled back, or even see what modifications a feature actually did. Also, when pushed one by one to origin (which hopefully would not happen frequently), this wastes CI server time with builds that will intentionally fail half of the time,

**-1) design**
Again, maybe something purely subjective, but I find it difficult to have a conversation on the structure of an entity without knowing what the actual use cases are that that part of the system will be responsible for.

**Comment by hassanhabib** [comment]
@Driedas  thank you for your dedication and your detailed identification of potential areas of growth in our architecture and technology.
let's start discussing your point one by one so we don't lose track.

>> 1) project structure
services, entities, API controllers everything in a single project. This would not be an issue on a small, single use, single logical deployment project. For anything larger than that, you will most likely have separate components, deployed separately (at least logically if not physically). For example handling background processes like sending emails, scheduled jobs, etc. All of these would need to host everything, including the API. It would make more sense to me to at least split out the model and services into separate assemblies and having the API as just an (or one of) optional communication layer on top of that.

The idea of building our components as brokers, services, controllers and models is that we are building vertical slices of flows for particular entities so eventually down the road it would be easier to split those off as microservices. 
Each microservice should by a slice of controller -> service -> broker and so on.
It doesn't seem like a good idea to think about componentization and modularization at this early stage, we have to start with one big monolith then later on break it down into microservices or components however you want to materialize them.

We try to build a monolith with a microservices mindset. meaning that we are building our monolith intentionally to be broken down eventually once the application gets larger (and it will) - and when that happen offline and online processes will need to be their own microservices, we will make that call when we get to that point, but for now, we shouldn't start optimizing for a workload and a size that we are not sure of yet.

A lot of people have asked me about the plan or big picture, or the high level goals, this is also very legit concern, however, as we are still simply just building the familiar entities of the system, I think that building these relationships and overviews are a bit too early.

We know that we want to build a schooling system, and that the system has students, classes, courses and teachers and exams, great let's start building those with full CRUD operations then we will discuss where to go from there, I like to plan for the foreseeable future not a year down the road, because I can guarantee you right now, that whatever we plan now is going to almost fully change by the time we get to where we are going, I am not a big fan of waterfalls :-)

**Comment by Driedas** [comment]
> We try to build a monolith with a microservices mindset. meaning that we are building our monolith intentionally to be broken down eventually once the application gets larger (and it will) - and when that happen offline and online processes will need to be their own microservices

That is fair enough, I can see this potentially working, however I am skeptical that the core domain (students, teachers, guardians, courses, exams) is ever going to be split into multiple microservices in the future as that is the very core functionality of the system. Who knows, hard to predict the future, I agree.
What I do see though is non-core concepts already bleeding over to the core, like UserId. Authentication is not a part of the core domain, the entities should not handle functionality like this. The opposite direction would make more sense to me, i. e. an authentication microservice whose only concern will be authentication (likely built on some product that already handles this domain) and the mapping of identities to students/teachers/guardians via a standard mechanism like claims.

> let's start building those with full CRUD operations

I don't see the core domain as a good candidate for a CRUD style approach (you don't create or update or delete a student or teacher), that's not how future users visualize an education system so there would be misunderstandings around the mappings of concepts like a student update to mark a student as graduated. There are more interesting concepts (and a ubiquitous language to be found), but this is a discussion for a later point.

> Let's discuss this first, then we will move on to the other points, I will use your initial post as an overview of what this thread's discussion is all about, does that sound like a good plan?

Awesome, I would also hope that at some point others would join in as well with their own suggestions and critique of my points as well.

**Comment by Driedas** [comment]
@hidegh entities and their serialization issues is a good point I missed. Given a rich model (e. g. a Student has a list of Subjects he attends and the Subject has a collection of Students that attend it) a serializer can easily keep on going and going when lazy loading is enabled. This is one of the very few instances where I saw a production server going down in flames with an out of memory exception :-)

**Comment by hassanhabib** [comment]
> > We try to build a monolith with a microservices mindset. meaning that we are building our monolith intentionally to be broken down eventually once the application gets larger (and it will) - and when that happen offline and online processes will need to be their own microservices
> 
> That is fair enough, I can see this potentially working, however I am skeptical that the core domain (students, teachers, guardians, courses, exams) is ever going to be split into multiple microservices in the future as that is the very core functionality of the system. Who knows, hard to predict the future, I agree.
> What I do see though is non-core concepts already bleeding over to the core, like UserId. Authentication is not a part of the core domain, the entities should not handle functionality like this. The opposite direction would make more sense to me, i. e. an authentication microservice whose only concern will be authentication (likely built on some product that already handles this domain) and the mapping of identities to students/teachers/guardians via a standard mechanism like claims.
> 
> > let's start building those with full CRUD operations
> 
> I don't see the core domain as a good candidate for a CRUD style approach (you don't create or update or delete a student or teacher), that's not how future users visualize an education system so there would be misunderstandings around the mappings of concepts like a student update to mark a student as graduated. There are more interesting concepts (and a ubiquitous language to be found), but this is a discussion for a later point.
> 
> > Let's discuss this first, then we will move on to the other points, I will use your initial post as an overview of what this thread's discussion is all about, does that sound like a good plan?
> 
> Awesome, I would also hope that at some point others would join in as well with their own suggestions and critique of my points as well.

@Driedas we create full CRUD operations on all entities not necessarily for business purposes, for instance, the delete or delete all operations, we have those so we can clean up what we create in our acceptance tests.
CRUD operations are also important to be able to modify a particular entity to validate a specific validation rule, the same thing goes with reporting for mid-layer entities that you don't necessarily have access to through admin or client portals there are so many scenarios there not all of them necessarily business related.

Now, regarding creating or deleting students ..etc - there's a higher layer of services that I call processing these processing services take care of these very specific business terminology and flows - watch this [video](https://www.youtube.com/watch?v=vZgPbneAdCM) to have a better view about these layers - the broker-neighboring services only run CRUD for entities, but any higher layer services will tell you something like: `DeactivateStudentAccount` and `ExpelStudent` ... etc etc.

These higher layer services might combine two or more basic operations from a broker-neighboring service to create a business value, sometimes it just calls one operation and give a different name and so on.
Does that make sense?

**Comment by Driedas** [comment]
> @Driedas we create full CRUD operations on all entities not necessarily for business purposes, for instance, the delete or delete all operations, we have those so we can clean up what we create in our acceptance tests.

Why not just create a throwaway database as part of the execution of acceptance tests? On test startup you generate an empty database with seed data and every test resets the database to the initial state (in whatever way, restore from a backup of the database generated in the beginning, or something like Respawn https://github.com/jbogard/Respawn).
Given you now have API endpoints for these operations, you have a vector of attack for potential bad actors, also service methods that anyone can call, but - if I understand you correctly - shouldn't outside of the scope of tests.

>CRUD operations are also important to be able to modify a particular entity to validate a specific validation rule, the same thing goes with reporting for mid-layer entities that you don't necessarily have access to through admin or client portals there are so many scenarios there not all of them necessarily business related.

If those CRUD operations are there for testing and reporting, sooner or later somebody will call them as part of his use case (because why not, they are there after all) and introduce inconsistencies by modifying data that only the system is allowed to. I wouldn't trust an audit trail of a system that even exposes CRUD semantics on top of its core domain.
For reports, it's best to bypass the model (as anemic as it currently is) and EF core entirely anyway and create custom projections that can be optimized on the database server side. EF core sucks for queries that are only slightly more complex than a query by ID - last time, not that long ago, I checked EF core executed aggregate operations on the client.

> Now, regarding creating or deleting students ..etc - there's a higher layer of services that I call processing these processing services take care of these very specific business terminology and flows (as long as they don't intersect with other entities, in which case they become orchesterators, coordinators or aggregators depends on how complex your business is)- watch this video to have a better view about these layers - the broker-neighboring services only run CRUD for entities, but any higher layer services will tell you something like: DeactivateStudentAccount and ExpelStudent ... etc etc.
These higher layer services might combine two or more basic operations from a broker-neighboring service to create a business value, sometimes it just calls one operation and give a different name and so on.
Does that make sense?

How and why? The current vertical slice already exposes CRUDs over the API. That's as high a layer as you can get. I think a sample would go a long way towards illustrating how that is supposed to look like. I saw the video before, and I agree on the public interface that should be exposed via the API (e. g. /students/1/deactivate) but that's not what I'm seeing in the vertical slice at the moment. Instead I see exposed CRUD methods that allow anyone (authenticated I assume?) to do anything.

**Comment by hassanhabib** [comment]
>> @Driedas we create full CRUD operations on all entities not necessarily for business purposes, for instance, the delete or delete all operations, we have those so we can clean up what we create in our acceptance tests.
>> Why not just create a throwaway database as part of the execution of acceptance tests? On test startup you generate an empty database with seed data and every test resets the database to the initial state (in whatever way, restore from a backup of the database generated in the beginning, or something like Respawn https://github.com/jbogard/Respawn).
Given you now have API endpoints for these operations, you have a vector of attack for potential bad actors, also service methods that anyone can call, but - if I understand you correctly - shouldn't outside of the scope of tests.

Creating a throwing away a temporary database doesn't give me the actual acceptance results considering we want to run this against live instances in the cloud - in which case that resetting option isn't really an option simply because we can't throw away our production database.
There's an infrastructural readiness aspect of these tests that is not yet visible because we are at early stages of the development process, Ideally I want to know that I can run a full happy path against the exact same components in my production environments and still be able to clean up the data I created without touching any other records.


>> CRUD operations are also important to be able to modify a particular entity to validate a specific validation rule, the same thing goes with reporting for mid-layer entities that you don't necessarily have access to through admin or client portals there are so many scenarios there not all of them necessarily business related.

>>If those CRUD operations are there for testing and reporting, sooner or later somebody will call them as part of his use case (because why not, they are there after all) and introduce inconsistencies by modifying data that only the system is allowed to. I wouldn't trust an audit trail of a system that even exposes CRUD semantics on top of its core domain.
For reports, it's best to bypass the model (as anemic as it currently is) and EF core entirely anyway and create custom projections that can be optimized on the database server side. EF core sucks for queries that are only slightly more complex than a query by ID - last time, not that long ago, I checked EF core executed aggregate operations on the client.

a lot of these non-business related CRUD operations endpoints will be private endpoints, hiding behind a middleware that requires particular roles, permissions and headers to be exposed and available only during particular test scenarios or reporting scenarios that team has to agree on, it's not free for all as some may think.
But the concept of private endpoints is very foreign, this is not the secure Azure private endpoints as some may think, it's a bit more than that - I will expand on that concept when the time comes.
You are jumping the gun a bit about what the end product is going to look like, there's more to what's being built currently than what's actually going to be delivered, exposed and deployed - we are just going to have to discuss that when we get there.

I am not sure what the complexity is of the queries that you have used with EF Core, I can only speak from my experience with large datasets, EF Core seemed to be doing a good job, but that's a different discussion for a different day.

>> Now, regarding creating or deleting students ..etc - there's a higher layer of services that I call processing these processing services take care of these very specific business terminology and flows (as long as they don't intersect with other entities, in which case they become orchesterators, coordinators or aggregators depends on how complex your business is)- watch this video to have a better view about these layers - the broker-neighboring services only run CRUD for entities, but any higher layer services will tell you something like: DeactivateStudentAccount and ExpelStudent ... etc etc.
These higher layer services might combine two or more basic operations from a broker-neighboring service to create a business value, sometimes it just calls one operation and give a different name and so on.
Does that make sense?

>> How and why? The current vertical slice already exposes CRUDs over the API. That's as high a layer as you can get. I think a sample would go a long way towards illustrating how that is supposed to look like. I saw the video before, and I agree on the public interface that should be exposed via the API (e. g. /students/1/deactivate) but that's not what I'm seeing in the vertical slice at the moment. Instead I see exposed CRUD methods that allow anyone (authenticated I assume?) to do anything.

As I said, these operations some of them are private endpoints, exposed for particular cases, if hit from outside they return 404 as in the URL itself doesn't exist, I don't have any published materials about this yet, but hopefully I will blog/vlog about it when time allows.

**Comment by Driedas** [comment]
Right, I get it, there is a bigger picture that I am not seeing yet. I'll take you by your word that there is a bigger picture and these pieces will somehow fall into place. To be honest, at the moment all of this seems to me like an extremely expensive test suite. I hope I'll get to eat my words with a side of humble pie down the line :-)

**Comment by hidegh** [comment]
@Driedas @hassanhabib 
**regarding testing and throw away database and crud brokers (and to it's mocked versions)**

with ORM the nice thing is, (if you avoid committing TX and/or using SaveChanges) that all your changes should be on the in memory ORM model. so you can do tests against! of course this works with some sample DB (or some seeding - even if in memory, or in a pre-seeded test DB).

is this not worth to consider?

***
There's one thing I did not really get, @hassanhabib wrote:
> Creating a throwing away a temporary database doesn't give me the actual acceptance results considering we want to run this against live instances in the cloud - in which case that resetting option isn't really an option simply because we can't throw away our production database.

It wasn't clear, but I assume we're talking about a copy of the production database - as there should be no tests executed on a production database, because...

So in this case it's just a copy you we're referring to. Now:
- **how does this copy differ from any temporary pre-seeded DB?**
- **And why should any kind of test depend on real, non static (changing) data?**
- What test cases should such unit test cover, considering that it's a CRUD (anemic) domain environment we're creating... I mean **in such cases here are even no stable data-rules inside or between entities enforced by the business logic - there's nothing really assumptions regard data we can rely on**

**Comment by chaouanabil** [comment]
Hi everyone,
Thank you @hassanhabib for this initiative, i did read the discussion about the architecturals and design choices. And i would like if you take a look guys in abp framework  https://abp.io/, because it promote to give a solution to a lot of points mentionned here like rich model vs anemic, cross edging concernes like entities validation , business rules validation, exception handling , authentication , tracing , auditing ...ect.

**Comment by hassanhabib** [comment]
> Hi everyone,
> Thank you @hassanhabib for this initiative, i did read the discussion about the architecturals and design choices. And i would like if you take a look guys in abp framework https://abp.io/, because it promote to give a solution to a lot of points mentionned here like rich model vs anemic, cross cutting concernes like entities validation , business rules validation, exception handling , authentication , tracing , auditing ...ect.

@chaouanabil thanks for sharing - this framework looks interesting definitely something to consider.

**Comment by hassanhabib** [comment]
> @Driedas @hassanhabib
> **regarding testing and throw away database and crud brokers (and to it's mocked versions)**
> 
> with ORM the nice thing is, (if you avoid committing TX and/or using SaveChanges) that all your changes should be on the in memory ORM model. so you can do tests against! of course this works with some sample DB (or some seeding - even if in memory, or in a pre-seeded test DB).
> 
> is this not worth to consider?
> 
> There's one thing I did not really get, @hassanhabib wrote:
> 
> > Creating a throwing away a temporary database doesn't give me the actual acceptance results considering we want to run this against live instances in the cloud - in which case that resetting option isn't really an option simply because we can't throw away our production database.
> 
> It wasn't clear, but I assume we're talking about a copy of the production database - as there should be no tests executed on a production database, because...
> 
> So in this case it's just a copy you we're referring to. Now:
> 
> * **how does this copy differ from any temporary pre-seeded DB?**
> * **And why should any kind of test depend on real, non static (changing) data?**
> * What test cases should such unit test cover, considering that it's a CRUD (anemic) domain environment we're creating... I mean **in such cases here are even no stable data-rules inside or between entities enforced by the business logic - there's nothing really assumptions regard data we can rely on**
> 
> Ohh and EF core: still miss SQL side grouping support (at least with OData it sill failed, see: [dotnet/efcore#10012](https://github.com/dotnet/efcore/issues/10012))

@hidegh I wasn't talking about a copy from a production database, I was talking about the actual database in production, running our acceptance tests against our production API and making sure we can run full cycle of CRUD operations (and orchestration, coordination, management and aggregation in the future) against the actual instance that everyone else is using.

These tests we run are great, but they are limited by the place and time they are running within. it still doesn't report the overall health status of the instance that everyone else is using and that's what I want a status report about.
If we run this in memory, we are not really getting the true status of our production environments, and therefore we are not getting a true health check/scan of full cycles of operations within our production instances. does that make sense?

**Comment by hassanhabib** [comment]
Shutting this down due to inactivity, feel free to revive if you have feedback.

**Comment by hassanhabib** [comment]
@devmanzur it depends on what you do with the exceptions.
In our case here exceptions are used to either terminate the current operation and report an error to the API consumer to fix their requests or an internal issue in which we report 5xx exceptions to end users and notify the engineers to handle the issue through logging.
we catch these inner exceptions for specific cases and wrap them in higher order exceptions so we can decide whether to just communicate a generic Bad Request 400 error or specify the error based on the case.
Exceptions are just as import as part of our business logic as everything else, the only difference is that we throw them when we decide the entire operation is invalid and we require external action to restart the operation.

Does that make sense?

**Comment by devmanzur** [comment]
I guess it makes sense for this context. Throwing exceptions makes the overall code simpler, But then we require creating a new exception type for each and every possible validation type.

**Comment by hassanhabib** [comment]
Awesome - please feel free to re-open if you have any further questions.

**Comment by youssefbennour** [comment]
@hassanhabib 
I've read that exceptions are very expensive and shouldn't be thrown for trivial validation scenarios (raising an exception for an invalid user password doesn't seem to be the right thing to do), so are there any good reason to stick with exceptions instead of using something like the 'ServiceResult' pattern ?

**Comment by devmanzur** [comment]
@youssefbennour I have been there, as you can see the last one to question this behavior 4 years ago was me :p. Result pattern is a valid approach and i use that too. Quoting the last sentence from @hassanhabib "Exceptions are just as import as part of our business logic as everything else, the only difference is that we throw them when we decide the entire operation is invalid and we require external action to restart the operation.".

As you will see in the framework itself. you can either choose to use SingleAsync or SingleOrDefaultAsync. one throws exception straight away, another allows you to handle the null value and do as you like. You will find both of them are valid approach and it comes down to design decision.

Exceptions are expensive but allowing user to continue when you encounter a invalid state might be more expensive.
