### ISSUE TITLE
Project improvements suggestion

### ISSUE THREAD

**Issue by sasestil** [hassanhabib/OtripleS#332]
Hello, 

First i want to thanks to  @hassanhabib for his initiation about project, contributors to this project, and for knowledge that you all are sharing with us

I have some suggestion that i think will improve project architecture. 

**1. Exceptions dependency**

**Problem:** I think that services (service layer) should not be coupled with exceptions from external library. Ex. "UserService.cs" is dependent on SqlException, DbUpdateException, DuplicateKeyException.... Let say that we want to replace Sql Server provider or EF, we must make correction in all services (in service layer).

**Solution:** One of the solution will be to create new exceptions for brokers (ex. for StorageBroker - StorageException, StorageUpdateException, StorageDuplicateKeyException ...) that will wrap external exception as inner exception and throw them from broker. Then in the service layer we can catch only broker exceptions. With that we can decouple service layer from external exceptions.

**2. Exceptions locations**
Will be better to move exceptions to nearby location from where exception is throw? Let say exceptions (ex. NullStudentException, NotFoundStudentException) that will be throw from "UserService.cs", to move to "Services\Users\Exceptions" directory. Same for Brokers. Ex. for "StorageBroker" exceptions (StorageException, StorageUpdateException, StorageDuplicateKeyException ...) to be located in "Brokers\StorageBroker\Exceptions".

**3. Brokers naming**
I think will be good to name brokers by technology that implement. Let say, storage broker (for sql server) name should be SqlServerStorageBroker.cs. For UserManagment should be IdentityUserManagment ... With this we can replace technology without changing current broker implementation. Also we can support multiple storage brokers (SqliteStorageBroker, MySqlStorageBroker ...).

**Comment by AgentEnder** [comment]
This should make a good discussion.

1. This is actually a pretty good catch, if using these introduces dependencies to EF that limits the usefulness of the brokers.
2. Brokers would throw the sql like exceptions purposefully, they are meant to just bridge between the api and its dependencies. Its the job of the services to translate that to user friendly output / exception types.
3. I don't agree with this one. This point directly contradicts point 1 IMHO, as the idea behind brokers is such that you should be able to swap out storage providers,  ORM's or other things without having to change the interface surface that you interact with.

**Comment by sasestil** [comment]
> 3\. I don't agree with this one. This point directly contradicts point 1 IMHO, as the idea behind brokers is such that you should be able to swap out storage providers,  ORM's or other things without having to change the interface surface that you interact with.

Sorry i give you a bad example. 
My point was not to change the interface surface, but only file names that implements that interface (ex. IStorageBroker.cs).

**Examples:**
IStorageBroker.cs
EFStorageBroker.cs
DapperStorageBroker.cs
NHibernateStorageBroker.cs

**and**
IUserManagerBroker.cs
IdentityServerUserManagerBroker.cs
OtherIdentityUserManagerBroker.cs

**and**
IDateTimeBroker.cs
SystemDateTimeBroker.cs
USBDongleDateTimeBroker.cs
NtpDateTimeBroker.cs

**and**
ILoggingBroker.cs
MicrosoftLoggingBroker.cs
NLogLoggingBroker.cs
SerilogLoggingBroker.cs

etc ...

**Comment by eriadhami** [comment]
I agree with @AgentEnder. 
Also i do not agree with the changing of broker names. Changing the names brings us to make changes in the Service layer tomorrow if we need to change or swap external libraries on the Broker layer. We will need changes also on the DI.

**Comment by hassanhabib** [comment]
@sasestil , @AgentEnder  and @eriadhami 
Thank you guys I appreciate the feedback.
here's a couple of things that come to mind when thinking about moving native exceptions to the brokers.
If you move these exceptions to the broker layer, we fall into a critical issue, which is that brokers become no longer a thin layer with no logic in it, they become mappers of native exceptions to local exceptions - this is problematic, because brokers are meant to be encapsulators and abstractors of native non-local models and functionality so our business layer is fully constituted out of local models.
In other words, if our brokers look something like this:
```csharp
public async ValueTask<Student> InsertStudentAsync(Student student)
{
    try
    {
           Student student = await this.Students.AddAsync(student);
           await this.SaveChangesAsync();
           
           return student;
    }
    catch (DuplicateKeyException duplicateKeyException)
    {
        throw new AlreadyExistsStudentException(duplicateKeyException);
    }
}
```
In this example above, we did _mapping_ from a native exception to a local exception out of the range of our tests. we intentionally don't test brokers, because they are merely exposing native APIs through a local contract like IStorageBroker. we don't want to test EF therefore we keep our brokers as far away as possible from any business-logic related operation, like if-else statements, for loops, mapping ... etc etc.

Now, if our brokers are outside of our realm of unit testing, then any code change could happen to this mapping that I did above without any issues being reported about the overall health of the application. acceptance and integration tests won't also catch that simply because they only target happy-paths and end to end integration validation scenarios. 

In other words, if I go and change the code above in my broker, no tests will fail. the application tests on all levels will report O.K as a test status, which is dangerous. 

In my engineering Standard I discussed this issue with a bit of detail in the sense that both your brokers, and your broker-neighboring services are sharing a portion of the responsibility of abstraction. your foundation (or broker-neighboring) services are not really 100% local, because they have to do some mapping to these native exceptions along with mapping to native model that may be returned when you use a 3rd party library to send emails for instance. the 3rd party will accept it's own native models such as `Email` for instance. your foundation services take care of doing that mapping.

Here's a diagram to explain where you application truly gets it's true abstraction and on which layers:


![image](https://user-images.githubusercontent.com/1453985/112713484-9caec180-8e92-11eb-9bcf-e6776ce76f88.png)

In the illustration above, if you considered the red color to represent native non-local models, like models you get from using a nuget library for instance, and if you consider the green to be your application local models the picture here should become clearer in terms of what really are the boundaries of your application.

It might come as a surprise to some, but your foundation services that just adds a layer of validations on top of the primitive operations your broker is already offering are not really fully local. they still have to deal with mapping your local models to native ones as needed, but more commonly they will map native exceptions to local ones. like how we do `DuplicateKeyException` to become `AlreadyExistsStudentException`.

Now, if you look again at the illustration above, you will notice that your true 100% local abstract operations happen at the processing level, it goes on through orchestration, coordination, management and aggregation level, and then it loses it's abstraction again once you start to communicate with exposers such as `Controllers` or `UI Components` or whatever the way you choose to expose your service APIs. 

It's not a coincidence that your processing layer has much more of what makes your application in general different from any other than your foundation layer. that's simply because your processing layer will start implementing functionality that is meaningful mainly to your business and not any other business. for instance, your processing layer services speak a language such as `EnsureStudentExsits` they combine multiple primitive operations to ensure a particular business goal is achieved which is what  I call a higher business order.  and that order happens to be more specific to the business than your typical CRUD operations that your foundation services would offer.


On the other topic, I don't mind the renaming of the concrete implementaions of brokers, so `IStorageBroker` to `StorageBroker` would be `IStorageBroker` to `SqlStorageBroker` or `CosmosStorageBroker` - that's not a big deal. however it doesn't seem to be very useful if you have only one technology that you are dealing with at all times. if you application communicates with `SQL` and only `SQL` then a generic name might not be too terrible. but if your application communicates with `Blob` storages and `SQL` and such then absolutely I would go for that.

I hope this addresses some of the questions, will follow up later with more insights.

**Comment by sasestil** [comment]
What if we create a base exceptions, let say for Storage Brokers:

StorageBrokerValidationException.cs
StorageBrokerDependencyException.cs
StorageBrokerServiceException.cs
DuplicateRecordException.cs
UpdateConcurrencyException.cs

then we map external exceptions to local storage exceptions, something like this:
```

private async ValueTask<TEntity> TryCatch(Func<ValueTask<TEntity>> returningFunction)
{
    try
    {
        return await returningFunction();
    }
    catch (SqlException sqlException)
    {
        if (sqlException.Number == 2627)
        {
            throw new StorageBrokerDependencyException(new DuplicateRecordException(sqlException));
        }

        throw new StorageBrokerDependencyException(sqlException);
    }
    catch (DbUpdateConcurrencyException dbUpdateConcurrencyException)
    {
        throw new StorageBrokerDependencyException(new UpdateConcurrencyException(dbUpdateConcurrencyException));
    }
    catch (DbUpdateException dbUpdateException)
    {
        throw new StorageBrokerDependencyException(dbUpdateException);
    }
    catch (Exception exception)
    {
        throw new StorageBrokerServiceException(exception);
    }
}
```

than in the service layer ex. UserService.cs we catch validation and only storage broker exceptions:
```

private async ValueTask<User> TryCatch(Func<ValueTask<User>> returningUserFunction)
{
    try
    {
        return await returningUserFunction();
    }
    catch (NullUserException nullUserException)
    {
        throw new UserValidationException(nullUserException);
    }
    catch (InvalidUserException invalidUserException)
    {
        throw new UserValidationException(invalidUserException);
    }
    catch (StorageBrokerValidationException exception)
    {
        if (exception.InnerException is DuplicateRecordException duplicateRecordException)
        {
            throw new UserValidationException(new AlreadyExistsUserException(duplicateRecordException));
        }

        throw new UserValidationException(exception);
    }
    catch (StorageBrokerDependencyException exception)
    {
        if (exception.InnerException is UpdateConcurrencyException updateConcurrencyException)
        {
            throw new UserDependencyException(new LockedUserException(updateConcurrencyException));
        }

        throw new UserDependencyException(exception);
    }
    catch (StorageBrokerServiceException exception)
    {
        throw new UserServiceException(exception);
    }
    catch(Exception exception)
    {
        throw new UserServiceException(exception);
    }
}

```
With this we move external exception dependency from service layer to broker layer, where i think it should belong.
Then if we want to change technology let say EF with Dapper, we only make change in the broker layer (we only create new DapperStorageBroker.cs file and its implementation).

**Comment by hassanhabib** [comment]
@sasestil thanks for your feedback, here's a couple of issues what that approach:
1. Not all brokers implement all CRUD operations at all times. there are cases where you need `DeleteAll` or `UpdateAll` the generic proposed interface doesn't really satisfy that condition. 
2. You are still handling and mapping exceptions on the broker level in your first code snippet. this means that you have business logic (the mapping) living outside of your scope of testing - which means that anyone could just modify that code without any failure on both unit and acceptance and integration levels.

**Comment by sasestil** [comment]
@hassanhabib 
> @sasestil thanks for your feedback, here's a couple of issues that approach:
> 
> 1. Not all brokers implement all CRUD operations at all times. there are cases where you need `DeleteAll` or `UpdateAll` the generic proposed interface doesn't really satisfy that condition.
> 2. You are still handling and mapping exceptions on the broker level in your first code snippet. this means that you have business logic (the mapping) living outside of your scope of testing - which means that anyone could just modify that code without any failure on both unit and acceptance and integration levels.

Yep i agree. It make sense.

But i have another dilemma. If we don't throw exception from broker then how we can handle external dependency exception that returned as result object (methods that does not throw exceptions). Let say for example UpdateUserAsync method in the UserManagmentBroker.cs 

```c#
public async ValueTask<User> UpdateUserAsync(User user)
{
    await this.userManagement.UpdateAsync(user);

    return user;
}
```
userManagement.UpdateAsync method returns result from operation

```c#
public async ValueTask<User> UpdateUserAsync(User user)
{
    IdentityResult result = await this.userManagement.UpdateAsync(user);

    if (!result.Succeeded)
    {
        var errors = result.Errors;

        // How to handle this. Should we throw some exception from here ?
    }

    return user;
}

```

**Comment by hassanhabib** [comment]
@sasestil That's a great question.
Foundation services (broker-neighboring services) are simply mappers on top of a validation layer. Mapping can mean that a returned value from an external dependency can also be converted to an exception if we need it to be. It can also be the other way around.
Here's a story for you. In one of the projects that I was working on, we had an SDK that sends emails - one of the issues with that external SDK is that it was throwing an exception instead of returning a `failed` status of some sort. 
Our code looked something like this on the foundation layer:

```csharp
try
{
    return returningMailStatusFunction();
}
catch (SomeExternalLibraryException someExternalException)
{
    return CreateAndLogFailedStatus(someException);
}

private MailStatus CreateAndLogFailedStatus(Exception exception)
{
    this.loggingBroker.LogError(exception);
    
    return MailStatus.Failed;
}
```

The opposite is also true, you are receiving a status and you want to throw an exception. Your code would then look something like this:

```csharp
public ValueTask<LocalUser> ModifyUserAsync(LocalUser localUser)
{
    User externalUser = MapToUser(localUser);
    IdentityResult result = await this.userManagementBroker.UpdateAsync(externalUser);
    ValidateUserModifyResult(result);
    
    return MapToLocalUser(result);
}
```
Then in your LocalUserService.Validations.cs file you would do something like this:

```csharp
private void ValidateUserModifyResult(IdentityResult result)
{
    if(result.Succeeded is false)
    {
        throw new LocalUserDependencyValidationException(result);
    }
}
```
You can see here that we have to paths of mapping a result. Either to a `LocalUser` in the case of a happy path. or a local exception that is `LocalUserDependencyValidationException` in case of failure. This way by the time you reach the next level on the processing layer, you are only dealing with local models either `LocalUser` or the local exception.

It's really important to make sure that all of these mappings happen on your foundation layer, so you can test what is actually happening. But remember, foundation layer services are not pure local. they are a hybrid component of both external and local models. You don't really get to a 100% pure logic until you hit a [Processing service](https://github.com/hassanhabib/The-Standard/blob/master/2.%20Services/2.1%20Processings/2.1%20Processings.md#22-processing-services-higher-order-business-logic).

Here's one more note about the code snippet you posted above. Your functions should be transparent about the status of of what happened within these functions. When you pass in a user and return whatever you passed in,

**Comment by StilSoft** [comment]
First,
Thank you very much for effort you put to give me such good explanation to my questions. Now things is much more clear to me. Now slowly i can see more big picture for how "The Standard" is conceived. I also have many more questions about arhitecture, especially about structure of projects. I still have dillema how to organize files in projects and solutions, where to put different type of services (Foundation, Processing, Orchestration etc.). Should i mix in the same project or to make different project for every service layer. I will try to find answers in the specification for "The Standard".

I just started big project that will fallow this arhitecture. Will see how thinks will go, while am working on the project. If i have more question about arhitecture, i will open issue in "The Standard" repo. I think that this type of question is more suited to be posted there. With that for people that have more questions about arhitecture maybe will be easier to find answers there.

Second,
There are so many thinks that people can learn from you, espesily how to look on thinks from another perspective, to see bigger picture, not only about programming and arhitecture, but also for thinks in theirs lifes.

Again, thank you very much.

**Comment by sasestil** [comment]
@hassanhabib 
First,
Thank you very much for effort you put to give me such good explanation to my questions. Now things is much more clear to me. Now slowly i can see more big picture for how "The Standard" is conceived. I also have many more questions about arhitecture, especially about structure of projects. I still have dillema how to organize files in projects and solutions, where to put different type of services (Foundation, Processing, Orchestration etc.). Should i mix in the same project or to make different project for every service layer. I will try to find answers in the specification for "The Standard".

I just started big project that will fallow this arhitecture. Will see how thinks will go, while am working on the project. If i have more question about arhitecture, i will open issue in "The Standard" repo. I think that this type of question is more suited to be posted there. With that for people that have more questions about arhitecture maybe will be easier to find answers there.

Second,
There are so many thinks that people can learn from you, espesily how to look on thinks from another perspective, to see bigger picture, not only about programming and arhitecture, but also for thinks in theirs lifes.

Again, thank you very much.

**Comment by hassanhabib** [comment]
@sasestil I'm always happy to hear feedback. Thank you for your kind words and your questions - looking forward to growing The Standard with intelligent engineers like yourself.

**Comment by hassanhabib** [comment]
Closing this issue - feel free to reopen or create a new one if you have any questions.
